### ISSUE TITLE
Cant connect to Dedicated Server

### ISSUE THREAD

**Issue by IsPherz** [JereKuusela/valheim-expand_world#18]
Hi Jere I been trying to use expand world to make my dedicated world bigger, the world generated fine I was able to join the first time with no issue then I logged out of it and restarted my game and tried joining again but I was unable it seemed I was about to get in but seems the game hanged up and stayed in the disconnection part of it cause it never returned to the title screen as shown below
![image](https://user-images.githubusercontent.com/11274437/206812281-75b6bec0-b677-4f08-9739-56251013bea4.png)

before that I joined the server but this is what I saw 
![image](https://user-images.githubusercontent.com/11274437/206812337-f85362d6-5b32-4bc4-b489-4d68d6a143f2.png)
I suppose this is due to expand world still working on but after a few mins the image above happens
these are the server logs
[LogOutput.log](https://github.com/JereKuusela/valheim-expand_world/files/10198741/LogOutput.log)
and the client logs
[LogOutput.log](https://github.com/JereKuusela/valheim-expand_world/files/10198742/LogOutput.log)

Can you tell me if maybe I messed up with anything? I will post the config files as well
Clients
[expand_world.cfg.log](https://github.com/JereKuusela/valheim-expand_world/files/10198746/expand_world.cfg.log)
and Servers
[expand_world.cfg.log](https://github.com/JereKuusela/valheim-expand_world/files/10198751/expand_world.cfg.log)

(Remove the .log of them)
is it because it takes too long to generate minimap?
![image](https://user-images.githubusercontent.com/11274437/206814130-2f6dfdb4-bd5a-4ace-b5f6-f0ee2796bd8b.png)
As additional context this is a whole new world created with the settings from above files

**Comment by metruzanca** [comment]
I also get this and the loadtime for each connection / loading the world is about 5 minutes.

**Comment by JereKuusela** [comment]
I increased the time out to 5 minutes. Minimap generation should also happen while in the game but maybe something has broken this.

I will try to investigate.
