### ISSUE TITLE
No Build in Locations

### ISSUE THREAD

**Issue by heberholanda** [JereKuusela/valheim-expand_world#20]
My friend, I created a world with this configuration. But even with this tag of **NoBuild: true** it is still possible to build in the region. Another question, would it be possible to specify the **size** of this NoBuild area?

- prefab: StoneCircle
  biome: Meadows, BlackForest
  quantity: 75
  minAltitude: 5
  minDistanceFromSimilar: 500
  randomRotation: true
  maxTerrainDelta: 2
  forestTresholdMin: 1
  forestTresholdMax: 8
  exteriorRadius: 16
  prioritized: true
  clearArea: true
  noBuild: true

**Comment by JereKuusela** [comment]
I'm actually currently working on this. I didn't realize no build requires data sync between the client and the server.

The size should be same as the exteriorRadius.

**Comment by heberholanda** [comment]
In my case, **Client and Server** have these settings, but it didn't work. I will wait for your updates.

Thanks for the extra information.
