### ISSUE TITLE
After death the dungeons becomming blocked

### ISSUE THREAD

**Issue by xzahalko** [JereKuusela/valheim-expand_world#22]
Hi, 
could you please check the old problem with the dungeons beeing blocked ?
We have tested new world with Expand world and without on local and with Expand world the problem after death is there.
Sometimes even without die in dungeon.

Thank you verry much for your help

**Comment by JereKuusela** [comment]
Do you happen to have CLLC installed?

**Comment by xzahalko** [comment]
Yes, while testing with and without Expand world we had CLLC installed.

**Comment by JereKuusela** [comment]
Thanks for the report. I will try to upload a fix today.
