### ISSUE TITLE
Using 'excludedRooms' property in dungeons.yml excludes all cloned versions of that room.

### ISSUE THREAD

**Issue by mdf25** [JereKuusela/valheim-expand_world#25]
For example if I had a room
```forestcrypt_new_Burialchamber05:Darkwoods```
And I add this to my dungeon
```excludedRooms:forestcrypt_new_Burialchamber05```
It also prevents the clone from being selected too.

**Comment by JereKuusela** [comment]
I wasn't able to reproduce this. Can you double check that all is setup correctly?

**Comment by mdf25** [comment]
It seemed to be, however since newest update I can't get the issue to reproduce either. Very odd. TY for checking :)
